
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * The "classic" engine config requires `datasource.url` at type level,
 * but we don't want `prisma generate` to fail during `docker build`
 * where DATABASE_URL is not set. We fall back to a harmless placeholder
 * — runtime connections still use the real DATABASE_URL from the schema.
 */
const databaseUrl =
  process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
